seed: 1
device: null
visualize: true # visualize results using trimesh
verbose: false
extrinsics_path: ./camera/workspace/calibration.json
data1: ./example_data/img/img_diana_original # reference
data2: ./example_data/img/20231010_monkey_test # test
hand_ref_pose_name: monkey # the ref pose is ./camera/hand_arm/ref_pose_{}.npy
model_path: ./example_data/pth/glayer_key0_pie_64_T0.007_20000.pth
img_preprocess:
  - sam
  - sam
scale: 14
dis_threshold: 0.1
quotient_threshold: 0.8
method: vote_3D # prune method
mode: hand
hand_model:
  tip_aug: 4
  pt_nums: 500
alignment:
  opt_iterations: 300